# Generated by Django 4.2.dev20220624125221 on 2022-07-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Name', models.CharField(max_length=50)),
                ('Problem_Description', models.TextField()),
                ('Problem_Difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('difficult', 'difficult')], default='easy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.FileField(upload_to='onlineJudge/test_input/')),
                ('test_output', models.FileField(upload_to='onlineJudge/test_output/')),
                ('Pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(choices=[('c++', 'cpp')], max_length=20)),
                ('Code_file', models.FileField(upload_to='onlineJudge/Code_file')),
                ('verdict', models.CharField(choices=[('PR', 'Processing'), ('WA', 'Wrong Answer'), ('AC', 'All Correct')], max_length=10)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('Pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.problems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
