# Generated by Django 4.2.dev20220624125221 on 2022-07-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problem_Name', models.CharField(max_length=50)),
                ('Problem_Description', models.TextField()),
                ('Problem_Difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('difficult', 'difficult')], default='easy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.FileField(upload_to='test_input/')),
                ('test_output', models.FileField(upload_to='test_output/')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(choices=[('c++', 'cpp'), ('c', 'c'), ('java', 'java'), ('python', 'python')], max_length=20)),
                ('Code_file', models.FileField(upload_to='Code_file')),
                ('verdict', models.CharField(choices=[('Exe', 'Executing'), ('WA', 'Wrong Answer'), ('AC', 'All Correct'), ('TLE', 'Time Limit Exeeded'), ('MLE', 'Memory Limit Exeeded')], max_length=10)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.problems')),
            ],
        ),
    ]
