# Generated by Django 4.2.dev20220624125221 on 2022-07-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='PID',
            new_name='Pname',
        ),
        migrations.RenameField(
            model_name='test_case',
            old_name='PID',
            new_name='Pname',
        ),
    ]
